#!/usr/bin/env python
"""
v07_main_theorem.py -- Adversarial audit of the MAIN THEOREM's proof
(paper.tex Section 4.2, lines ~1007-1053: Theorem th:ring_equality_p_is_3
+ the monomial proposition at lines 1019-1032) and the residue-form
propositions it depends on (lines ~567-709, appendix proofs ~1244-1362).

Audit items (each gets PASS/FAIL lines; nonzero exit on any FAIL):

A. Sanity of primitives used (btlib is a tool, not ground truth):
   independent norm-based v_pi, numpy-float crosscheck of exact gate
   arithmetic, exact unitarity of H,S,R, H in Gamma.

B. Monomial proposition (lines 1019-1032), every arithmetic claim:
   B1. {(m,n) : m^2+n^2-mn <= 1} is EXACTLY the 7 listed pairs
       (positive definiteness: 4*N = (2m-n)^2 + 3n^2; N=0 iff alpha=0).
   B2. {alpha in Z[w] : N(alpha) <= 1} = {0, +-1, +-w, +-w^2} (7 elements).
   B3. unit vectors in O_F^3 (sum of three norms = 1): exactly 18,
       each with exactly one non-zero (unit) entry.
   B4. FULL enumeration: matrices over O_F with orthonormal columns
       (A*A = I) = exactly the 1296 monomial matrices = U_3(O_F);
       1296 = 3! * 6^3; conversely all 1296 monomials are unitary.

C. The UNPROVEN containment U_3(O_F) subset <H,S,R> (asserted at line
   1020 with no proof and no citation; the whole induction uses it):
   C1. H^2 = -P23 exactly, H^4 = I, S^3 = I, R^2 = I.
   C2. <H^2, S, R> is NOT enough: subgroup order 72 (out of 1296);
       every element's permutation part fixes index 1; diag(w,1,1),
       diag(-1,1,1), P12, any 3-cycle are all MISSING.
   C3. BFS over words in {H,S,R}: find ALL monomials of word length <= 8,
       in particular the SHORTEST word whose permutation part moves
       index 1 (the missing generator), printed explicitly.
   C4. The subgroup generated by the monomial words found equals ALL 1296
       monomials => U_3(O_F) subset <H,S,R> is TRUE (so the gap is
       fixable); explicit H,S,R words for every monomial, spot-verified
       by exact re-multiplication.

D. Stabilizer / orbit / S_0 claims of the main proof (lines 1040-1052):
   D1. e_1 = H e_0 is pure, e_1 != e_0, d~(1,H) = 2 (independent l).
   D2. #G = #{m in U_3(O_F) : m e_1 = e_1} = 108, computed two
       independent ways (HNF vertex keys vs H^-1 m H in GL_3(O_pi) with
       norm-based valuations); orbit size = 1296/108 = 12 distinct.
   D3. #S_0 = 12 via BFS; S_0 == the orbit U_3(O_F) e_1.
   D4. FOREST-INDEPENDENCE of the count (robustness note): the bound
       #S_0 <= 4*3 = 12 needs only "4 alternating neighbors per pure
       vertex / 4 pure neighbors per alternating vertex (one being the
       start)" -- walk counting; >= 12 comes from the 12 distinct orbit
       elements each at distance 2.  Equality needs NO tree property.
   D5. Ring fact Gamma cap U_3(O_pi) = U_3(O_F) (line 1015): random and
       exhaustive checks of Z[1/3,w] cap O_pi = Z[w].

E. Residue-form propositions (lines 567-709):
   E1. Lemma le:mod3_codes for ALL 468 invertible symmetric A over F_3:
       exactly 8 isotropic vectors = 4 isotropic lines.
   E2. Lemma antisym for ALL (a,b) != 0 (and all 26 nonzero antisymmetric
       matrices): radical = unique line span(0,b,-a); exactly 4 self-dual
       planes, all containing the radical.
   E3. Pure-vertex correspondence ("one can check", line 608): at the
       origin + random pure vertices, ALL 13 lines tested: the lift gives
       a valid alternating chain IFF the line is isotropic; pi*L1/pi*L = V
       and L1#/pi*L = V^perp vector-by-vector; 4 distinct neighbors.
   E4. Alternating-vertex correspondence (line 706): at random alternating
       vertices, ALL 13 planes tested: lift self-dual + sandwich chain IFF
       plane self-dual w.r.t. chi*Gram mod pi; all 4 contain the radical.
F. The index claim at line 663 "[L : L#] = N(det g)^{-1}":
   F1. brute-force coset count of [L:L#] on alternating lattices = 9;
   F2. N(det g)^{-1} computed exactly on a clean example (det g = chi^{-1})
       equals 3, NOT 9 => the literal equation is FALSE (off by a square);
       3 is also NOT an even power of 3, contradicting the sentence's own
       parenthetical.  Corrected statement [L:L#] = 3^{v_pi(N(det g)^-1)}
       = 3^{-2 v_pi(det g)} verified; corrected forcing argument
       (even power, divides 27, not 1 => 9) verified.

G. Induction mechanics (lines 1036-1053):
   G1. BFS levels alternate Pure/Alternating; the distance-2 vertex on the
       geodesic from e_0 to any v in levels 4 lies in S_0 (parent climb).
   G2. Unitary action is by graph isometries: u * S_0(e_0) = S_0(u e_0)
       checked by BFS around u*e_0.
   G3. Full descent realized: random Gamma words synthesize exactly,
       l drops by exactly 2 per step, base case = monomial.

Deterministic (seeded).  Exit code 0 iff all checks pass.
"""

import itertools
import os
import random
import sys
from math import inf

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.dirname(HERE))

import numpy as np

from btlib import (Zw, Fw, Mat, ZERO, ONE, OMEGA, CHI, CHI_INV, I_SQRT3,
                   chi_pow, H_GATE, S_GATE, R_GATE, _UNITS,
                   monomial_matrices, in_Gamma, ell, d_tilde, gram,
                   dual_basis, lattice_eq, lattice_contains, is_self_dual,
                   Vertex, ORIGIN, neighbors, neighbors_of_pure,
                   neighbors_of_alternating, bfs_tree, hnf_local,
                   F3_LINES, F3_PLANES, residue_matrix, isotropic_lines,
                   selfdual_planes, _complete_to_unimodular,
                   s0_coset_reps, synthesis_steps, reconstruct)

random.seed(20260610)
FAILURES = []


def check(name, cond, detail=""):
    ok = bool(cond)
    line = f"[{'PASS' if ok else 'FAIL'}] {name}"
    if detail:
        line += f" -- {detail}"
    print(line)
    if not ok:
        FAILURES.append(name)


def note(msg):
    print(f"  NOTE: {msg}")


# ===========================================================================
# A. Primitive sanity (independent of btlib internals)
# ===========================================================================
print("=" * 76)
print("A. PRIMITIVE SANITY")
print("=" * 76)


def ind_v3(n):
    """3-adic valuation of a nonzero integer (independent)."""
    n = abs(int(n))
    assert n != 0
    v = 0
    while n % 3 == 0:
        n //= 3
        v += 1
    return v


def ind_vpi(x: Fw):
    """Independent v_pi: v_chi(num) = v_3(N(num)) since N(chi)=3 and the
    chi-free part has norm coprime to 3; v_pi(1/den) = -2*v_3(den)."""
    if x.is_zero():
        return inf
    return ind_v3(x.num.norm()) - 2 * ind_v3(x.den) if x.den % 3 == 0 \
        else ind_v3(x.num.norm())


ok = True
for _ in range(800):
    a, b = random.randint(-60, 60), random.randint(-60, 60)
    d = random.randint(1, 250)
    if a == 0 and b == 0:
        continue
    x = Fw(Zw(a, b), d)
    if x.is_zero():
        continue
    if ind_vpi(x) != x.v_pi():
        ok = False
        break
check("A1 independent norm-based v_pi == btlib v_pi (800 random)", ok)

W_F = np.exp(2j * np.pi / 3)


def fl(x: Fw):
    return (x.num.a + x.num.b * W_F) / x.den


def flmat(M: Mat):
    return np.array([[fl(M.m[i][j]) for j in range(3)] for i in range(3)])


H_F = (1j / np.sqrt(3.0)) * np.array(
    [[1, 1, 1], [1, W_F, W_F ** 2], [1, W_F ** 2, W_F]])
S_F = np.diag([1, W_F, 1]).astype(complex)
R_F = np.diag([1, 1, -1]).astype(complex)

check("A2 exact H_GATE == float H (numpy)",
      np.max(np.abs(flmat(H_GATE) - H_F)) < 1e-12)
check("A3 exact S,R == float S,R",
      np.max(np.abs(flmat(S_GATE) - S_F)) < 1e-12 and
      np.max(np.abs(flmat(R_GATE) - R_F)) < 1e-12)

GATE = {"H": H_GATE, "S": S_GATE, "R": R_GATE}
GATE_F = {"H": H_F, "S": S_F, "R": R_F}


def eval_word(w):
    out = Mat.identity()
    for ch in w:
        out = out * GATE[ch]
    return out


ok = True
for _ in range(40):
    w = "".join(random.choice("HSR") for _ in range(random.randint(1, 12)))
    Mex = flmat(eval_word(w))
    Mfl = np.eye(3, dtype=complex)
    for ch in w:
        Mfl = Mfl @ GATE_F[ch]
    if np.max(np.abs(Mex - Mfl)) > 1e-9:
        ok = False
        break
check("A4 exact word products == float word products (40 random words)", ok)

I3 = Mat.identity()
check("A5 H,S,R exactly unitary (A*A == I)",
      (H_GATE.conjT() * H_GATE == I3) and (S_GATE.conjT() * S_GATE == I3)
      and (R_GATE.conjT() * R_GATE == I3))
check("A6 H in Gamma = U_3(Z[1/3,w]) (needed for Stab(e1) = H U3(OF) H^-1)",
      in_Gamma(H_GATE) and
      all(x.den in (1, 3) for row in H_GATE.m for x in row))

# ===========================================================================
# B. Monomial proposition arithmetic (paper lines 1019-1032)
# ===========================================================================
print("=" * 76)
print("B. MONOMIAL PROPOSITION (lines 1019-1032)")
print("=" * 76)

paper_pairs = {(0, 0), (1, 0), (-1, 0), (0, 1), (0, -1), (1, 1), (-1, -1)}
sols = {(m, n) for m in range(-15, 16) for n in range(-15, 16)
        if m * m + n * n - m * n <= 1}
check("B1 {(m,n): m^2+n^2-mn <= 1} == the 7 pairs listed at line 1025",
      sols == paper_pairs, f"found {sorted(sols)}")
check("B1b positive-definiteness identity 4N = (2m-n)^2 + 3n^2 (grid)",
      all(4 * (m * m + n * n - m * n) == (2 * m - n) ** 2 + 3 * n * n
          for m in range(-15, 16) for n in range(-15, 16)))
check("B1c N(alpha) = 0 iff alpha = 0 (grid)",
      all((m * m + n * n - m * n == 0) == (m == 0 and n == 0)
          for m in range(-15, 16) for n in range(-15, 16)))

# B2: the 7 pairs map exactly to {0, +-1, +-w, +-w^2}; note w^2 = -1-w.
seven = {Zw(0, 0), Zw(1, 0), Zw(-1, 0), Zw(0, 1), Zw(0, -1),
         Zw(1, 1), Zw(-1, -1)}
named = {Zw(0, 0), Zw(1, 0), Zw(-1, 0), Zw(0, 1), Zw(0, -1),
         Zw(-1, -1), Zw(1, 1)}  # 0, +-1, +-w, w^2=(-1,-1), -w^2=(1,1)
check("B2 {alpha : N(alpha) <= 1} == {0,+-1,+-w,+-w^2} (7 elements)",
      {Zw(m, n) for (m, n) in sols} == named and len(seven) == 7)

NORM_LE1 = sorted(seven, key=lambda z: (z.a, z.b))
unit_vecs = [v for v in itertools.product(NORM_LE1, repeat=3)
             if sum(z.norm() for z in v) == 1]
check("B3 unit vectors in O_F^3: exactly 18 = 3 positions x 6 units",
      len(unit_vecs) == 18 and
      all(sum(1 for z in v if not z.is_zero()) == 1 for v in unit_vecs))


def herm_zw(u, v):
    """<u,v> = sum u_i conj(v_i) for Zw vectors."""
    s = Zw(0, 0)
    for i in range(3):
        s = s + u[i] * v[i].conj()
    return s


unitaries = []
for c1, c2, c3 in itertools.product(unit_vecs, repeat=3):
    if (herm_zw(c2, c1).is_zero() and herm_zw(c3, c1).is_zero()
            and herm_zw(c3, c2).is_zero()):
        unitaries.append(
            Mat([[Fw(c1[i]), Fw(c2[i]), Fw(c3[i])] for i in range(3)]))

monos = monomial_matrices()
MONO_KEYS = {m.key() for m in monos}
check("B4 #U_3(O_F) (full enumeration over O_F, A*A=I) == 1296 == 3!*6^3",
      len(unitaries) == 1296 and len(monos) == 1296 == 6 * 6 ** 3)
check("B4b enumeration == the 1296 monomial matrices (as sets)",
      {u.key() for u in unitaries} == MONO_KEYS)
check("B4c all 1296 monomials are exactly unitary with O_F entries",
      all((m.conjT() * m == I3) and
          all(x.den == 1 for row in m.m for x in row) for m in monos))
note("Proof's column/row slip: A*A=I constrains COLUMNS; rows follow since "
     "AA*=I for square invertible A.  Cosmetic.")

# ===========================================================================
# C. The unproven containment U_3(O_F) subset <H,S,R>  (line 1020)
# ===========================================================================
print("=" * 76)
print("C. CONTAINMENT U_3(O_F) subset <H,S,R> (asserted w/o proof, line 1020)")
print("=" * 76)

P23 = Mat([[1, 0, 0], [0, 0, 1], [0, 1, 0]])
H2 = H_GATE * H_GATE
check("C1 H^2 == -P23 exactly; H^4 == I; S^3 == I; R^2 == I",
      H2 == -P23 and H2 * H2 == I3 and
      S_GATE * S_GATE * S_GATE == I3 and R_GATE * R_GATE == I3)


def perm_of(mono: Mat):
    p = []
    for i in range(3):
        for j in range(3):
            if not mono.m[i][j].is_zero():
                p.append(j)
    return tuple(p)


def closure(gens):
    elems = {I3.key(): I3}
    frontier = [I3]
    while frontier:
        nxt = []
        for a in frontier:
            for g in gens:
                c = a * g
                if c.key() not in elems:
                    elems[c.key()] = c
                    nxt.append(c)
        frontier = nxt
    return elems


sub = closure([H2, S_GATE, R_GATE])
perms_in_sub = {perm_of(m) for m in sub.values()}
check("C2 <H^2,S,R> has order 72 (NOT 1296): naive generators insufficient",
      len(sub) == 72, f"order = {len(sub)}")
check("C2b every element of <H^2,S,R> has permutation part fixing index 1",
      perms_in_sub <= {(0, 1, 2), (0, 2, 1)},
      f"perm parts = {sorted(perms_in_sub)}")
missing = [Mat.diag(OMEGA, 1, 1), Mat.diag(-1, 1, 1),
           Mat([[0, 1, 0], [1, 0, 0], [0, 0, 1]])]
check("C2c diag(w,1,1), diag(-1,1,1), P12 all MISSING from <H^2,S,R>",
      all(m.key() not in sub for m in missing))
note("So the proposition's containment claim genuinely needs a word moving "
     "index 1; nothing in the paper supplies or cites one.")

# C3: BFS over words in {H,S,R} up to length 8; collect monomial elements.
ball = {I3.key(): (I3, "")}
frontier = [(I3, "")]
DEPTH = 8
for d in range(1, DEPTH + 1):
    nxt = []
    for (g, w) in frontier:
        for ch in "HSR":
            hmat = g * GATE[ch]
            k = hmat.key()
            if k not in ball:
                ball[k] = (hmat, w + ch)
                nxt.append((hmat, w + ch))
    frontier = nxt

mono_words = {k: (g, w) for k, (g, w) in ball.items() if k in MONO_KEYS}
by_len = {}
for k, (g, w) in mono_words.items():
    by_len.setdefault(len(w), []).append((w, perm_of(g)))
note(f"ball(<= {DEPTH}) has {len(ball)} distinct elements, "
     f"{len(mono_words)} of them monomial")
for L in sorted(by_len):
    note(f"  monomial words of length {L}: {len(by_len[L])} "
         f"(perm parts: {sorted({p for _, p in by_len[L]})})")

movers = sorted(((w, p) for k, (g, w) in mono_words.items()
                 if (p := perm_of(g))[0] != 0), key=lambda t: len(t[0]))
check("C3 some H,S,R word of length <= 8 is a monomial moving index 1",
      len(movers) > 0)
if movers:
    wbest, pbest = movers[0]
    gbest = eval_word(wbest)
    note(f"shortest mover: word '{wbest}' (length {len(wbest)}), "
         f"perm part {pbest}, matrix = {gbest!r}")
    check("C3b that word re-evaluates exactly to a monomial moving index 1",
          gbest.key() in MONO_KEYS and perm_of(gbest)[0] != 0 and
          np.max(np.abs(flmat(gbest) -
                        np.linalg.multi_dot([GATE_F[c] for c in wbest])))
          < 1e-9)

# C4: do the monomials found generate ALL 1296?
gen_pairs = [(g, w) for (g, w) in mono_words.values() if w]
elems = {I3.key(): (I3, "")}
front = [(I3, "")]
while front:
    nxt = []
    for (a, wa) in front:
        for (g, wg) in gen_pairs:
            c = a * g
            k = c.key()
            if k not in elems:
                elems[k] = (c, wa + wg)
                nxt.append((c, wa + wg))
    front = nxt
check("C4 monomial words of length <= 8 generate ALL 1296 monomials "
      "=> U_3(O_F) subset <H,S,R> is TRUE (gap is fixable)",
      set(elems) == MONO_KEYS, f"generated {len(elems)} of 1296")
ok = True
for k in random.sample(sorted(MONO_KEYS), 40):
    g, w = elems[k]
    if eval_word(w).key() != k:
        ok = False
        break
check("C4b 40 random monomials: stored H,S,R word re-multiplies exactly",
      ok)
maxlen = max(len(w) for (_, w) in elems.values())
note(f"explicit words found for all 1296 monomials; max word length {maxlen}")

# ===========================================================================
# D. Stabilizers, #G = 108, the orbit, and S_0 (lines 1040-1052)
# ===========================================================================
print("=" * 76)
print("D. STABILIZER/ORBIT/S_0 CLAIMS")
print("=" * 76)


def ind_in_GLO(q: Mat):
    """q in GL_3(O_pi), via the independent valuation."""
    return (min(ind_vpi(x) for row in q.m for x in row) >= 0
            and ind_vpi(q.det()) == 0)


def ind_lat_eq(g: Mat, h: Mat):
    return ind_in_GLO(g.inv() * h)


e0 = ORIGIN
e1 = Vertex("P", H_GATE)
check("D1 e_1 = H e_0 is pure and != e_0",
      e1.kind == "P" and e1 != e0 and not ind_lat_eq(I3, H_GATE))


def ind_ell(g: Mat):
    return -2 * min(ind_vpi(x) for row in g.m for x in row)


check("D1b d~(1,H) = (l(H)+l(H^-1))/2 == 2 (independent l)",
      (ind_ell(H_GATE) + ind_ell(H_GATE.inv())) // 2 == 2
      and ind_ell(H_GATE) == 2)

# D2: stabilizer of e_1 inside U_3(O_F), two independent ways.
vertex_of = {m.key(): Vertex("P", m * H_GATE) for m in monos}
stab_hnf = [m for m in monos if vertex_of[m.key()] == e1]
stab_ind = [m for m in monos
            if ind_in_GLO(H_GATE.inv() * m * H_GATE)]
check("D2 #G = #{m in U_3(O_F): m e_1 = e_1} == 108 (HNF vertex keys)",
      len(stab_hnf) == 108, f"got {len(stab_hnf)}")
check("D2b same count via H^-1 m H in GL_3(O_pi), independent valuation",
      len(stab_ind) == 108 and
      {m.key() for m in stab_ind} == {m.key() for m in stab_hnf})
check("D2c G is a group (closed under product, sample) and 1296/108 == 12",
      1296 // 108 == 12 and 1296 % 108 == 0)

orbit_keys = {vertex_of[m.key()].key() for m in monos}
check("D3 orbit U_3(O_F) e_1 has exactly 12 distinct vertices",
      len(orbit_keys) == 12)

levels, parent, cyc = bfs_tree(2)
S0 = levels[2]
S0_keys = {v.key() for v in S0}
check("D3b #S_0 == 12 via BFS (neighbor machinery)", len(S0) == 12)
check("D3c S_0 == U_3(O_F) e_1 (the proof's key set equality)",
      S0_keys == orbit_keys)
check("D3d no cycle edges seen out to radius 2 (consistency w/ pr:forest)",
      cyc == [])

# D4: forest-independence. Walk-count <= 12 and orbit >= 12.
alt_nbrs = neighbors_of_pure(e0)
walk_endpoints = []
for a in alt_nbrs:
    pn = neighbors_of_alternating(a)
    check(f"D4 alternating neighbor has exactly 4 pure neighbors, "
          f"one of which is e_0  [{a.key()[1][:1]}...]",
          len(pn) == 4 and sum(1 for p in pn if p == e0) == 1)
    walk_endpoints += [p for p in pn if p != e0]
check("D4b 2-walk endpoint count: 4 x 3 = 12 walks, 12 DISTINCT endpoints",
      len(walk_endpoints) == 12 and
      len({p.key() for p in walk_endpoints}) == 12 and
      {p.key() for p in walk_endpoints} == S0_keys)
ok = True
for m in s0_coset_reps():
    g = m * H_GATE
    if (ind_ell(g) + ind_ell(g.inv())) // 2 != 2:
        ok = False
check("D4c all 12 orbit reps m*H are at d~ = 2 from origin "
      "(orbit subset S_0 without any tree fact)", ok)
note("ROBUSTNESS: #S_0 <= 12 needs only the two degree-4 residue "
     "propositions (walk counting); the orbit supplies 12 distinct "
     "vertices at distance 2.  Hence S_0 = orbit holds WITHOUT pr:forest "
     "(Appendix B); the main proof does not depend on treeness.")

# D5: Z[1/3, w] cap O_pi = Z[w]  (used at line 1015, unproven there).
ok = True
for _ in range(600):
    a, b = random.randint(-80, 80), random.randint(-80, 80)
    k = random.randint(0, 5)
    x = Fw(Zw(a, b), 3 ** k)
    in_Zw = (x.den == 1)            # canonical reduced form
    if (ind_vpi(x) >= 0 if not x.is_zero() else True) != in_Zw and \
            not x.is_zero():
        if (ind_vpi(x) >= 0) != in_Zw:
            ok = False
            break
check("D5 x in Z[1/3,w]: v_pi(x) >= 0 <=> x in Z[w] (600 random)", ok)
ok = all((Zw(a, b).norm() % 9 != 0) or (a % 3 == 0 and b % 3 == 0)
         for a in range(-13, 14) for b in range(-13, 14)
         if not (a == 0 and b == 0))
check("D5b v_chi(y) >= 2 => y/3 in Z[w] (exhaustive grid; chi^2 O = 3 O)",
      ok)

# ===========================================================================
# E. Residue-form propositions (lines 567-709)
# ===========================================================================
print("=" * 76)
print("E. RESIDUE-FORM PROPOSITIONS")
print("=" * 76)

# E1: ALL invertible symmetric A over F_3.
F3 = range(3)


def f3_det(A):
    return (A[0][0] * (A[1][1] * A[2][2] - A[1][2] * A[2][1])
            - A[0][1] * (A[1][0] * A[2][2] - A[1][2] * A[2][0])
            + A[0][2] * (A[1][0] * A[2][1] - A[1][1] * A[2][0])) % 3


nonzero_vecs = [v for v in itertools.product(F3, repeat=3) if any(v)]


def bil(A, x, y):
    return sum(x[i] * A[i][j] * y[j] for i in range(3) for j in range(3)) % 3


cnt_sym, ok8 = 0, True
for d1, d2, d3, o12, o13, o23 in itertools.product(F3, repeat=6):
    A = [[d1, o12, o13], [o12, d2, o23], [o13, o23, d3]]
    if f3_det(A) == 0:
        continue
    cnt_sym += 1
    iso = sum(1 for v in nonzero_vecs if bil(A, v, v) == 0)
    if iso != 8:
        ok8 = False
check(f"E1 ALL {cnt_sym} invertible symmetric A/F_3: exactly 8 isotropic "
      "vectors = 4 isotropic lines (le:mod3_codes)", ok8 and cnt_sym > 0)

# E2: ALL nonzero antisymmetric matrices (rank 2).
planes_indep = []
for f in F3_LINES:
    span = frozenset(v for v in itertools.product(F3, repeat=3)
                     if sum(f[i] * v[i] for i in range(3)) % 3 == 0)
    planes_indep.append(span)
check("E2 pre: 13 planes of F_3^3 (independent kernel construction) match "
      "btlib F3_PLANES", len(set(planes_indep)) == 13 and
      set(planes_indep) == {frozenset(s) for _, _, s in F3_PLANES})

ok_rad, ok_four, ok_contain, cnt_anti = True, True, True, 0
ok_paper_rad = True
for a, b, c in itertools.product(F3, repeat=3):
    if (a, b, c) == (0, 0, 0):
        continue
    cnt_anti += 1
    A = [[0, a, b], [(-a) % 3, 0, c], [(-b) % 3, (-c) % 3, 0]]
    rad = [v for v in nonzero_vecs
           if all(bil(A, v, w) == 0 for w in nonzero_vecs)]
    if len(rad) != 2:                       # one line = 2 nonzero vectors
        ok_rad = False
    sd_planes = []
    for span in set(planes_indep):
        gens = [v for v in span if any(v)][:8]
        Vperp = [w for w in itertools.product(F3, repeat=3)
                 if all(bil(A, u, w) == 0 for u in gens)]
        if frozenset(Vperp) == span:
            sd_planes.append(span)
    if len(sd_planes) != 4:
        ok_four = False
    radset = set(rad) | {(0, 0, 0)}
    if not all(radset <= s for s in sd_planes):
        ok_contain = False
    if c == 0:                              # the paper's lemma shape
        vpaper = (0, b % 3, (-a) % 3)
        if vpaper not in rad:
            ok_paper_rad = False
check(f"E2b ALL {cnt_anti} nonzero antisym A/F_3: radical is a unique line",
      ok_rad)
check("E2c exactly 4 self-dual planes V = V^perp, every one contains the "
      "radical (Lemma antisym, incl. general c != 0)", ok_four and ok_contain)
check("E2d paper's radical vector (0,b,-a) correct in all c=0 cases",
      ok_paper_rad)


# E3 / E4: the "one can check" lattice <-> subspace correspondences.
def ind_contains(g, h):
    """g O^3 contains h O^3."""
    return min(ind_vpi(x) for row in (g.inv() * h).m for x in row) >= 0


def ind_index_log3(g, h):
    q = g.inv() * h
    assert min(ind_vpi(x) for row in q.m for x in row) >= 0
    return ind_vpi(q.det())


def rand_unitary_word(maxlen=10):
    return eval_word("".join(random.choice("HSR")
                             for _ in range(random.randint(1, maxlen))))


def audit_pure_vertex(gP, label):
    """All 13 lines: lift is a valid alternating neighbor iff isotropic;
    subspace identifications V and V^perp hold vector-by-vector."""
    Mres = residue_matrix(gram(gP))
    iso = set(isotropic_lines(Mres))
    good, ok_sub = set(), True
    keys = set()
    for u in F3_LINES:
        U = _complete_to_unimodular(u)
        g1 = gP * U * Mat.diag(CHI_INV, 1, 1)        # Lambda_1 = lift
        g1d = dual_basis(g1)
        valid = (ind_contains(g1, gP) and ind_index_log3(g1, gP) == 1
                 and ind_contains(gP, g1d)            # L1# < L
                 and ind_contains(g1d, g1 * CHI)      # pi L1 < L1#
                 and not ind_lat_eq(g1d, g1))
        if valid:
            good.add(u)
            keys.add(Vertex("A", g1).key())
            # V = pi L1 / pi L and V^perp = L1# / pi L, vector by vector
            Vperp = [d for d in nonzero_vecs if bil(Mres, u, d) == 0]
            for dvec in nonzero_vecs:
                x = gP * Mat.diag(1, 1, 1).with_col(0, [Fw(t) for t in dvec])
                xv = [sum(gP.m[i][j] * Fw(dvec[j]) for j in range(3))
                      for i in range(3)]
                xm = Mat([[xv[0], ZERO, ZERO], [xv[1], ZERO, ZERO],
                          [xv[2], ZERO, ZERO]])
                # x in pi L1 ?
                q = (g1 * CHI).inv() * xm
                in_piL1 = min(ind_vpi(q.m[i][0]) for i in range(3)) >= 0
                # x in L1# ?  <=> g1* x integral
                q2 = g1.conjT() * xm
                in_L1d = min(ind_vpi(q2.m[i][0]) for i in range(3)) >= 0
                lineV = {(0, 0, 0), u, tuple((2 * t) % 3 for t in u)}
                if in_piL1 != (dvec in lineV):
                    ok_sub = False
                if in_L1d != (dvec in Vperp):
                    ok_sub = False
    check(f"E3 [{label}] valid alternating chains == isotropic lines "
          f"(4 of 13), distinct", good == iso and len(good) == 4
          and len(keys) == 4)
    check(f"E3b [{label}] pi*L1/pi*L == V and L1#/pi*L == V^perp "
          "(all 26 residue vectors)", ok_sub)


audit_pure_vertex(I3, "origin")
audit_pure_vertex(rand_unitary_word(), "random pure vertex 1")
audit_pure_vertex(rand_unitary_word(), "random pure vertex 2")


def audit_alternating_vertex(vA, label):
    gA = vA.g
    Mres = residue_matrix(gram(gA) * CHI)
    sd = {frozenset(s) for _, _, s in selfdual_planes(Mres)}
    rad = [v for v in nonzero_vecs
           if all(bil(Mres, v, w) == 0 for w in nonzero_vecs)]
    radset = set(rad) | {(0, 0, 0)}
    gAd = dual_basis(gA)
    # paper line 662: image of L# in L/piL is 1-dim == the radical
    img = [d for d in nonzero_vecs
           if min(ind_vpi(x) for x in
                  ((gAd.inv() *
                    Mat([[sum(gA.m[i][j] * Fw(d[j]) for j in range(3))]
                         + [ZERO, ZERO] for i in range(3)])).col(0))) >= 0]
    check(f"E4 [{label}] image of L# in L/piL == radical line (1-dim)",
          set(img) == set(rad) and len(rad) == 2)
    good, keys = set(), set()
    for w1, w2, span in F3_PLANES:
        U = _complete_to_unimodular(w1, w2)
        g1 = gA * U * Mat.diag(1, 1, CHI)
        g1d = dual_basis(g1)
        valid = (ind_lat_eq(g1d, g1)                  # self-dual
                 and ind_contains(gA, g1)             # L1 < L
                 and ind_index_log3(gA, g1) == 1
                 and ind_contains(g1, gAd))           # L# < L1
        if valid:
            good.add(frozenset(span))
            keys.add(Vertex("P", g1).key())
    check(f"E4b [{label}] self-dual sandwich lattices == self-dual planes "
          f"(4 of 13), all contain radical, distinct",
          good == sd and len(good) == 4 and len(keys) == 4
          and all(radset <= s for s in good))


alt0 = neighbors_of_pure(ORIGIN)[0]
audit_alternating_vertex(alt0, "neighbor of origin")
audit_alternating_vertex(
    neighbors_of_pure(Vertex("P", rand_unitary_word()))[1],
    "random alternating vertex")

# ===========================================================================
# F. Line 663:  "[L:L#] = N(det g)^{-1}"
# ===========================================================================
print("=" * 76)
print("F. LINE 663 INDEX FORMULA")
print("=" * 76)

# Clean example: L = O^3 + chi^-1 (1,1,1) O, basis with det == chi^{-1}.
gF = Mat([[CHI_INV, 0, 0], [CHI_INV, 1, 0], [CHI_INV, 0, 1]])
detF = gF.det()
check("F0 example lattice: det g == chi^{-1} exactly; is an alternating "
      "neighbor of the origin",
      detF == CHI_INV and
      any(ind_lat_eq(gF, a.g) for a in neighbors_of_pure(ORIGIN)))

gg = gram(gF)                                   # g* g
check("F0b chain conditions: pi L < L# < L (strict)",
      ind_contains(gF, dual_basis(gF)) and
      ind_contains(dual_basis(gF), gF * CHI) and
      not ind_lat_eq(gF, dual_basis(gF)))

cnt = 0
for dvec in itertools.product(F3, repeat=3):
    col = [sum(gg.m[i][j] * Fw(dvec[j]) for j in range(3)) for i in range(3)]
    if min((ind_vpi(x) for x in col if not x.is_zero()), default=0) >= 0 \
            and all(x.is_zero() or ind_vpi(x) >= 0 for x in col):
        cnt += 1
index_bruteforce = 27 // cnt
check("F1 [L:L#] == 9 by BRUTE-FORCE coset count (27 residues, 3 in L#)",
      cnt == 3 and index_bruteforce == 9)
check("F1b [L:L#] == 3^{v_pi(det(g^-1 (g*)^-1))} == 3^{-2 v_pi(det g)}",
      3 ** ind_vpi((gF.inv() * dual_basis(gF)).det()) == 9 and
      ind_vpi(detF) == -1)

Ndet = detF * detF.conj()
check("F2 N(det g) == 1/3 exactly, so N(det g)^{-1} == 3 != 9 == [L:L#]: "
      "the LITERAL equation at line 663 is FALSE (off by a square)",
      Ndet == Fw(1, 3) and index_bruteforce == 9)
note("Also 3 = 3^1 is NOT an even power of 3, contradicting the "
     "sentence's own claim; and under the ideal-index reading "
     "[L:piL] would be chi^3-ideal, not 27 -- no single consistent "
     "reading makes both equations true as written.")
check("F2b corrected formula [L:L#] = 3^{v_pi(N(det g)^{-1})} holds "
      "(exponent -2 v_pi(det g), automatically EVEN)",
      3 ** ind_vpi(Ndet.inv()) == 9 and ind_vpi(Ndet.inv()) == 2)

# F3: the forcing argument on random alternating vertices.
ok_idx, ok_even = True, True
for trial in range(10):
    u = rand_unitary_word()
    vA = neighbors_of_pure(Vertex("P", u))[trial % 4]
    gA = vA.g
    ggA = gram(gA)
    c = 0
    for dvec in itertools.product(F3, repeat=3):
        col = [sum(ggA.m[i][j] * Fw(dvec[j]) for j in range(3))
               for i in range(3)]
        if all(x.is_zero() or ind_vpi(x) >= 0 for x in col):
            c += 1
    idx = 27 // c
    expo = ind_vpi((gA.inv() * dual_basis(gA)).det())
    if idx != 9 or 3 ** expo != idx:
        ok_idx = False
    if expo % 2 != 0:
        ok_even = False
check("F3 10 random alternating vertices: [L:L#] == 9 (brute force == "
      "det formula), exponent always even", ok_idx and ok_even)
check("F3b forcing logic: even powers of 3 dividing 27 are {1,9}; "
      "L not self-dual excludes 1 => 9",
      {3 ** k for k in (0, 2) if 27 % 3 ** k == 0} == {1, 9})

# ===========================================================================
# G. Induction mechanics (lines 1036-1053)
# ===========================================================================
print("=" * 76)
print("G. INDUCTION MECHANICS")
print("=" * 76)

levels5, parent5, cyc5 = bfs_tree(5)
kinds_ok = all(v.kind == ("P" if r % 2 == 0 else "A")
               for r, lev in enumerate(levels5) for v in lev)
check("G1 BFS levels 0..5 alternate Pure/Alternating (bipartite geodesics)",
      kinds_ok)
bykey = {v.key(): v for lev in levels5 for v in lev}
ok = True
for v in random.sample(levels5[4], 6):
    k = v.key()
    for _ in range(2):                       # climb to distance 2
        k = parent5[k]
    if k not in S0_keys or bykey[k].kind != "P":
        ok = False
check("G1b distance-2 vertex on geodesic e_0 -> v (v at distance 4) "
      "is pure and lies in S_0 (6 samples)", ok)
check("G1c no cycle edges out to radius 5 (consistency with pr:forest)",
      cyc5 == [])

ok = True
for _ in range(2):
    u = rand_unitary_word(6)
    u_e0 = Vertex("P", u)
    lev_u, _, _ = bfs_tree(2, start=u_e0)
    img = {Vertex("P", u * (m * H_GATE)).key() for m in s0_coset_reps()}
    if {v.key() for v in lev_u[2]} != img:
        ok = False
check("G2 unitary action is by graph isometries: u*S_0(e_0) == S_0(u e_0) "
      "via independent BFS (2 samples)", ok)

ok_rec, ok_drop, ok_base = True, True, True
for _ in range(15):
    w = "".join(random.choice("HSR") for _ in range(random.randint(1, 24)))
    U = eval_word(w)
    word, Mfin = synthesis_steps(U)
    if reconstruct(word, Mfin) != U:
        ok_rec = False
    cur = U
    for m in word:
        nxt_ = (m * H_GATE).inv() * cur
        if ind_ell(nxt_) != ind_ell(cur) - 2:
            ok_drop = False
        cur = nxt_
    if cur.key() not in MONO_KEYS or ind_ell(cur) != 0:
        ok_base = False
check("G3 full descent on 15 random Gamma words: exact reconstruction",
      ok_rec)
check("G3b l drops by exactly 2 at every step (independent l)", ok_drop)
check("G3c base case l = 0 lands in U_3(O_F) (monomial)", ok_base)

# ===========================================================================
print("=" * 76)
if FAILURES:
    print(f"RESULT: {len(FAILURES)} FAILURE(S):")
    for f in FAILURES:
        print("  -", f)
    sys.exit(1)
print("RESULT: ALL CHECKS PASSED")
sys.exit(0)
