// Contract simulation: feed the EXACT engine JSON for trajectory(word='HSHHHSH')
// (fixture generated by vizgen.walks via .venv python — see fixtures/hshhhsh.json)
// through the compiled walk-reduction bookkeeping (computeTokenFates) and assert
// the token-lifetime invariants of DATA_CONTRACT.md.

import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { computeTokenFates, pathEdges } from './build/walk.js';

const here = dirname(fileURLToPath(import.meta.url));
const traj = JSON.parse(readFileSync(join(here, 'fixtures', 'hshhhsh.json'), 'utf8'));

let n = 0;
function assert(cond, label) {
  n++;
  if (!cond) {
    console.error(`FAIL [${label}]`);
    process.exit(1);
  }
}

// fixture sanity (the engine's own invariants)
assert(traj.ok === true, 'fixture ok');
assert(traj.word === 'HSHHHSH', 'fixture word');
assert(traj.sde === 0, 'T = HSHHHSH is a monomial: sde 0');
const hLetters = traj.steps.filter((s) => s.type === 'move').length;
assert(hLetters === 5, '5 H letters');
assert(traj.trail.length - 1 === 2 * hLetters, 'len(trail) − 1 = 2 · #H');
assert(traj.edgeOwner.length === traj.trail.length - 1, 'one owner per trail edge');

// --- the bookkeeping under test ---------------------------------------------
const fates = computeTokenFates(traj.trail, traj.edgeOwner, traj.reduction);

assert(fates.events.length === 5, `5 reduction events (got ${fates.events.length})`);
assert(fates.hCount === 5, '5 H tokens tracked');
assert(
  fates.fates.length === 5 && fates.fates.every((f) => f === 'dead'),
  `all 5 H tokens dead at the end (got ${JSON.stringify(fates.fates)})`,
);
assert(fates.survivingFull === 0, `0 survivors (got ${fates.survivingFull})`);
assert(fates.survivingEdges === 0, '0 surviving trail edges');
assert(fates.survivingEdges / 2 === traj.sde, 'surviving edges / 2 = sde (meter invariant)');
assert(
  JSON.stringify(fates.finalTrail) === JSON.stringify(traj.geodesic),
  'replaying the schedule on the trail yields exactly the geodesic',
);

// every event removes a genuine backtrack lobe and reports its owners
for (const ev of fates.events) {
  assert(ev.lobe[0] === ev.lobe[2], 'lobe is a backtrack (equal outer vertices)');
  assert(ev.edgeOwners.length === 2, 'two edge owners per event');
}

// per-event death/half accounting sums to the 5 tokens
const allDied = fates.events.flatMap((e) => e.died);
assert(allDied.length === 5, 'each H dies exactly once across the schedule');
assert(new Set(allDied).size === 5, 'no double deaths');

// pathEdges helper consistency
assert(pathEdges(traj.geodesic).length === traj.geodesic.length - 1, 'pathEdges length');
assert(pathEdges(['']).length === 0, 'pathEdges of a single vertex is empty');

// --- invariant sweep over more engine trajectories ---------------------------
// fixtures/extra_trajs.json: HH, HSH, ωI (len 21), −I (len 15), random-40 (seed 7)
// generated by vizgen.walks.trajectory via .venv python.
const extra = JSON.parse(readFileSync(join(here, 'fixtures', 'extra_trajs.json'), 'utf8'));
for (const t of extra) {
  const f = computeTokenFates(t.trail, t.edgeOwner, t.reduction);
  const halves = f.fates.filter((x) => x === 'half').length;
  const w = t.word ?? '(matrix)';
  assert(
    JSON.stringify(f.finalTrail) === JSON.stringify(t.geodesic),
    `${w}: schedule replay reaches the geodesic`,
  );
  assert(f.survivingEdges === 2 * t.sde, `${w}: surviving edges = 2·sde`);
  // half tokens pair up: 2·full + halves = 2·sde (lateral moves half-cancel)
  assert(2 * f.survivingFull + halves === 2 * t.sde, `${w}: 2·full + half = 2·sde`);
  assert(f.events.length === t.reduction.length, `${w}: all events replayed`);
}

console.log(`contract.test.mjs: all ${n} assertions passed`);
console.log(
  `  HSHHHSH: ${fates.events.length} events, fates=${JSON.stringify(fates.fates)}, ` +
    `survivors=${fates.survivingFull}, sde=${traj.sde}`,
);
console.log(`  + invariant sweep over ${extra.length} more engine trajectories (incl. random-40)`);
