/*
 * pyodide.test.mjs — the deployable-build consistency proof.
 *
 * Loads the verified Python (btlib + vizgen) under Pyodide (WASM CPython),
 * exactly as the deployed Web Worker does, and asserts its webapi.handle output
 * is BYTE-IDENTICAL to native CPython (fixtures generated by .venv/bin/python).
 * This proves the deployed site computes the same exact arithmetic as the local
 * engine — no drift, no fork.
 *
 * Run: node test/pyodide.test.mjs   (after `npm run build:web` so dist/py exists)
 */
import { loadPyodide } from 'pyodide';
import { readFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const pyDir = resolve(here, '..', 'dist', 'py'); // the BUILT, deployed copies
const fixtures = JSON.parse(
  readFileSync(resolve(here, 'fixtures', 'pyodide_expected.json'), 'utf8'),
);

const FILES = [
  'btlib.py',
  'vizgen/__init__.py',
  'vizgen/treegen.py',
  'vizgen/serialize.py',
  'vizgen/walks.py',
  'vizgen/webapi.py',
];

console.log('loading Pyodide (WASM CPython)…');
const pyodide = await loadPyodide();
pyodide.FS.mkdirTree('/py/vizgen');
for (const f of FILES) {
  pyodide.FS.writeFile('/py/' + f, readFileSync(resolve(pyDir, f), 'utf8'));
}
pyodide.runPython('import sys; sys.path.insert(0, "/py")');
const handle = pyodide.runPython(`
import json
from vizgen import webapi
def _h(op, pj):
    status, data = webapi.handle(op, json.loads(pj) if pj else {})
    return json.dumps({"status": status, "data": json.dumps(data, sort_keys=True)})
_h
`);

let fails = 0;
for (const fx of fixtures) {
  const out = JSON.parse(handle(fx.op, JSON.stringify(fx.payload)));
  const okStatus = out.status === fx.status;
  const okData = out.data === fx.data; // both are sort_keys JSON strings
  const tag = fx.op + '(' + JSON.stringify(fx.payload).slice(0, 40) + ')';
  if (okStatus && okData) {
    console.log(`[PASS] ${tag}`);
  } else {
    fails++;
    console.log(`[FAIL] ${tag}`);
    if (!okStatus) console.log(`   status ${out.status} != ${fx.status}`);
    if (!okData) {
      console.log(`   pyodide: ${out.data.slice(0, 200)}`);
      console.log(`   native : ${fx.data.slice(0, 200)}`);
    }
  }
}

console.log('');
if (fails) {
  console.log(`pyodide.test.mjs: ${fails}/${fixtures.length} FAILED`);
  process.exit(1);
}
console.log(`pyodide.test.mjs: all ${fixtures.length} fixtures byte-identical to native CPython ✓`);
